version: '2.4'

services:

  db:
    extends:
      file: docker/common/app-pg.yml
      service: postgres

    env_file:
      - .env

  cassandra_node_1:
    extends:
      file: docker/common/cassandra.yml
      service: cassandra

    env_file:
      - .env

  cassandra_node_2:
    extends:
      file: docker/common/cassandra.yml
      service: cassandra2

    env_file:
      - .env

  cassandra_node_3:
    extends:
      file: docker/common/cassandra.yml
      service: cassandra3

    env_file:
      - .env

  app:

    depends_on:
      - db

    extends:
      file: docker/common/app-pg.yml
      service: app

    env_file:
      - .env

networks:
  webnet:

volumes:
  pg_data:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local
  cassandra3_data:
    driver: local