version: '2.4'

services:

  db:
    extends:
      file: docker/common/app.yml
      service: postgres

    env_file:
      - .env

  zabbix-server:
    extends:
      file: docker/common/zabbix.yml
      service: zabbix-server

    env_file:
      - .env

    depends_on:
      - db

  zabbix-web:
    extends:
      file: docker/common/zabbix.yml
      service: zabbix-web

    env_file:
      - .env

    depends_on:
      - db
      - zabbix-server

  zabbix-agent:
    extends:
      file: docker/common/zabbix.yml
      service: zabbix-agent

    env_file:
      - .env

    depends_on:
      - db
      - zabbix-server

  cache:
    extends:
      file: docker/common/app.yml
      service: redis

    env_file:
      - .env

  rabbit-1:
    extends:
      file: docker/rabbitmq/rabbitmq.yml
      service: rabbit-1

    env_file:
      - .env

  rabbit-2:
    extends:
      file: docker/rabbitmq/rabbitmq.yml
      service: rabbit-2

    depends_on:
      - rabbit-1

    env_file:
      - .env

  rabbit-3:
    extends:
      file: docker/rabbitmq/rabbitmq.yml
      service: rabbit-3

    depends_on:
      - rabbit-1

    env_file:
      - .env

  app:

    depends_on:
      - db

    extends:
      file: docker/common/app.yml
      service: app

    env_file:
      - .env

  scheduler:

    depends_on:
      - app

    extends:
      file: docker/common/app.yml
      service: celery

    env_file:
      - .env

networks:
  webnet: