version: '2.4'

services:

  db:
    extends:
      file: docker/common/app.yml
      service: postgres

    env_file:
      - .env

  cache:
    extends:
      file: docker/common/app.yml
      service: redis

    env_file:
      - .env

  rabbit-1:
    extends:
      file: docker/rabbitmq/rabbitmq.yml
      service: rabbit-1

    env_file:
      - .env

  rabbit-2:
    extends:
      file: docker/rabbitmq/rabbitmq.yml
      service: rabbit-2

    depends_on:
      - rabbit-1

    env_file:
      - .env

  rabbit-3:
    extends:
      file: docker/rabbitmq/rabbitmq.yml
      service: rabbit-3

    depends_on:
      - rabbit-1

    env_file:
      - .env

  exporter:
    extends:
      file: docker/monitoring/prom.yml
      service: exporter

    depends_on:
      - rabbit-1

    env_file:
      - .env

  prometheus:
    extends:
      file: docker/monitoring/prom.yml
      service: prometheus

    depends_on:
      - exporter

  grafana:
    extends:
      file: docker/monitoring/prom.yml
      service: grafana

    depends_on:
      - prometheus

  app:

    depends_on:
      - db

    extends:
      file: docker/common/app.yml
      service: app

    env_file:
      - .env

  scheduler:

    depends_on:
      - app

    extends:
      file: docker/common/app.yml
      service: celery

    env_file:
      - .env

networks:
  webnet: