version: '2.4'

services:

  postgres:

    networks:
      - webnet

    image: 'timescale/timescaledb-postgis:1.4.2-pg11'
    container_name: tl_postgres
    ports:
      - 5432:5432

  redis:

    networks:
      - webnet

    image: 'redis:5.0.7-alpine'
    container_name: tl_redis
    ports:
      - 6379:6379

  app:

    networks:
      - webnet

    image: 'romanidze/tl_app:latest'

    build:

      target: development_build
      context: ../../
      dockerfile: docker/django/Dockerfile
      args:
        DOCKERIZE_VERSION: ${DOCKERIZE_VERSION}
        POETRY_VERSION: ${POETRY_VERSION}
        DJANGO_ENV: ${DJANGO_ENV}
        DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}

    container_name: tl_app
    volumes:
      - ../../:/code
      - ../../docker/django/entrypoint.sh:/usr/local/bin/entrypoint.sh
    ports:
      - 8000:8000
    command: start-dev

  celery:

    image: 'romanidze/tl_app:latest'

    networks:
      - webnet

    container_name: tl_celery
    volumes:
      - ../../:/code
    command: start-celery

networks:
  webnet: