version: '2.4'

services:

  postgres:

    networks:
      - webnet

    image: 'kartoza/postgis:12.0'
    container_name: tl_postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:

    networks:
      - webnet

    image: 'redis:5.0.7-alpine'
    container_name: tl_redis
    ports:
      - 6379:6379

  app:

    networks:
      - webnet

    image: 'romanidze/tl_app:latest'

    build:

      target: development_build
      context: ../../
      dockerfile: docker/django/Dockerfile

    container_name: tl_app
    volumes:
      - ../../:/code
      - ../../docker/django/entrypoint.sh:/usr/local/bin/entrypoint.sh
    ports:
      - 8000:8000
    command: start-dev

  celery:

    image: 'romanidze/tl_app:latest'

    networks:
      - webnet

    container_name: tl_celery
    volumes:
      - ../../:/code
    command: start-celery

networks:
  webnet:

volumes:
  pg_data: