version: '2.4'
services:
  cassandra:

    networks:
      - webnet

    container_name: tl_cassandra_1

    image: 'bitnami/cassandra:3.11.5'

    ports:
      - 7000:7000
      - 9042:9042

    volumes:
      - ../cassandra/cql:/docker-entrypoint-initdb.d

  cassandra2:

    networks:
      - webnet

    container_name: tl_cassandra_2

    image: 'bitnami/cassandra:3.11.5'

    ports:
      - 7001:7000
      - 9043:9042

  cassandra3:

    networks:
      - webnet

    container_name: tl_cassandra_3

    image: 'bitnami/cassandra:3.11.5'

    ports:
      - 7002:7000
      - 9044:9042

networks:
  webnet: