version: '2.4'
services:
  
  cassandra:

    networks:
      - webnet

    container_name: tl_cassandra_1

    image: 'bitnami/cassandra:3.11.5'

    ports:
      - 7000:7000
      - 9042:9042

    environment:
      - CASSANDRA_SEEDS=tl_cassandra_1,tl_cassandra_2,tl_cassandra_3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=200M

    volumes:
      - ../cql:/docker-entrypoint-initdb.d

  cassandra2:

    networks:
      - webnet

    container_name: tl_cassandra_2

    image: 'bitnami/cassandra:3.11.5'

    ports:
      - 7001:7000
      - 9043:9042

    environment:
      - CASSANDRA_SEEDS=tl_cassandra_1,tl_cassandra_2,tl_cassandra_3
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=200M

  cassandra3:

    networks:
      - webnet

    container_name: tl_cassandra_3

    image: 'bitnami/cassandra:3.11.5'

    environment:
      - CASSANDRA_SEEDS=tl_cassandra_1,tl_cassandra_2,tl_cassandra_3
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=200M

    ports:
      - 7002:7000
      - 9044:9042

networks:
  webnet: