# Generated by Django 2.2.6 on 2019-10-20 08:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('target', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='TripToProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(db_column='profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile')),
                ('trip', models.ForeignKey(db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.Trip')),
            ],
            options={
                'db_table': 'trip_to_profile',
            },
        ),
    ]
