
global:
  external_labels:
      monitor: 'rabbitmq-monitor'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['tl_prometheus:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['tl_rabbit_exporter:9090']