domain: ''

secret_key: 'asfdlnan3o49rj94jofewmcdsozixjp90womed,sa[0op'

jdbc:
  name: 'transportik_db'
  host: 'tl_postgres'
  port: 5432
  user: 'zabbix'
  password: 'zabbix'
  engine: 'django.contrib.gis.db.backends.postgis'
  conn_max_age: 60

jwt:
  verify_token: true
  verify_expiration: true
  expiration_time: 3000
  header: 'Bearer'

cassandra:
  contact_points: ['tl_cassandra_1', 'tl_cassandra_2', 'tl_cassandra_3']
  port: 9042
  keyspace: 'default'
  table_name: 'transport_analysis'

redis:
  host: 'tl_redis'
  port: 6379
  db: 0

rabbitmq:
  host: 'rabbit-1'
  port: 15672
  user: 'tl_user'
  password: 'tl_pass'
