# Generated by Django 2.2.6 on 2019-10-20 09:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import transportik.modules.transports.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('tonnage', models.IntegerField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(choices=[(transportik.modules.transports.enums.TransportType(1), 1), (transportik.modules.transports.enums.TransportType(2), 2), (transportik.modules.transports.enums.TransportType(3), 3)])),
            ],
            options={
                'db_table': 'transport_info',
            },
        ),
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('transport', models.ForeignKey(db_column='transport_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.TransportInfo')),
                ('trip', models.ForeignKey(db_column='trip_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.Trip')),
            ],
            options={
                'db_table': 'trip_info',
            },
        ),
        migrations.CreateModel(
            name='TransportPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transport', models.ForeignKey(db_column='transport_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transports.TransportInfo')),
            ],
            options={
                'db_table': 'transport_position',
            },
        ),
    ]
